// 06_frameworks/02_react/src/NameInput/NameInput.jsx
import {useState} from "react";

const NameInput = () => {
    const [name, setName] = useState('')

    return (
        <div className="textbox">
            <div>
                <span>Profile - </span>
                <span>First Name: </span>
                <span className="name">{name}</span>
            </div>
            <input type="text"
                   value={name}
                   placeholder="Name"
                   onInput={event => setName(event.target.value)}
            />
        </div>
    )
}
export default NameInput

// 06_frameworks/03_vue/src/components/NameInput.vue
<template>
  <div class="textbox">
    <div>
      <span>Profile - </span>
      <span>First Name:</span>
      <span class="name">{{name}}</span>
    </div>
    <input type="text"
           placeholder="Name"
           v-model="name"
    />
  </div>
</template>

<script setup>
import {ref} from "vue";
const name = ref('')
</script>
